### PR TITLE
fix: fix issues

### LINKED ISSUE #530: [多数据源导入] 本地文件弹窗内表头状态更新不正确
本地文件表头状态

### LINKED ISSUE #532: [Schema] 添加属性 数据类型置灰不可点击
image

### PR DESCRIPTION
**Pull request by hetao92**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
- fix #532 
- fix #530

### CODE REVIEW

File: app/components/FileConfigSetting/index.tsx [hunk 1]
```diff
@@ -117,7 +117,7 @@ const FileConfigSetting = (props: IProps) => {
     e.stopPropagation();
     const isActive = activeItem?.uid === data[index].uid;
     const newData = data.filter((_, i) => i !== index);
-    const checkedNum = data.reduce((n, file) => n + (file.withHeader & 1), 0);
+    const checkedNum = newData.reduce((n, file) => n + (file.withHeader & 1), 0);
```
Comment (huaxiabuluo) [inline app/components/FileConfigSetting/index.tsx]:
```ts
const checkedNum = data.reduce((n, file, i) => n + ((i !== index && file.withHeader) & 1), 0);
```

**Review by huaxiabuluo — APPROVED** [review]
LGTM
