### PR TITLE
fix: fix some issues

### LINKED ISSUE #529: The tab character used as a prefix, cannot find this data.
When a tab is added in front of 'vid', the data cannot be queried, but it can be found through visual query.Need to join\t
e.g. vid: " 11"

截屏2023-04-06 16 30 33
A1D53EB3-FD1A-4E89-8194-7E44BA79E3E1
A13F2B15-64B2-4544-88EF-EA20A93DF26C

### LINKED ISSUE #536: [多数据源导入] 本地csv文件没有内容 页面展示按钮超出边界
image

### LINKED ISSUE #537: [多数据源导入] sf100 nebula服务挂掉 停止任务失败
环境：192.168.8.131:7001
host：192.168.8.237:9669
image

### LINKED ISSUE #538: [多数据源导入] 数据源列表 s3编辑时填写错误信息报错信息不明确
image

### LINKED ISSUE #539: [多数据源导入] 停止导入任务接口未返回结果 需要手动刷新
image

### LINKED ISSUE #540: [多数据源导入] 调用批量删除接口 传参不存在的数据源id 返回的message不正确
1. 调用数据源批量删除接口
2. 示例 id为12的数据源不存在
3. message应报错 不存在 目前是test
image

### PR DESCRIPTION
**Pull request by hetao92**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
- fix #536 
- fix #537 
- fix #538 
- fix #539 
- fix #540 
- fix #529

### CODE REVIEW

File: server/api/studio/internal/service/datasource.go [hunk 1]
```diff
@@ -182,16 +182,35 @@ func (d *datasourceService) Remove(request types.DatasourceRemoveRequest) error
...
 }
 
+func contains(s []int, e int) bool {
+	for _, a := range s {
+		if a == e {
+			return true
+		}
+	}
+	return false
+}
```
Comment (huaxiabuluo) [inline server/api/studio/internal/service/datasource.go]:
```go
lo.Contains
```

File: app/utils/function.ts [hunk 2]
```diff
@@ -11,11 +11,7 @@ export const handleVidStringName = (name: string, spaceVidType?: string) => {
   if (spaceVidType && spaceVidType === 'INT64') {
     return convertBigNumberToString(name);
   }
-  if (name.indexOf(`"`) > -1 && name.indexOf(`'`) === -1) {
-    return `'${name}'`;
-  } else {
-    return `"${name}"`;
-  }
+  return JSON.stringify(name);
```
Comment (huaxiabuluo) [inline app/utils/function.ts:16]: add some comments and explanations ?

**Review by huaxiabuluo — APPROVED** [review]
LGTM
