### PR TITLE
fix: fix issues

### LINKED ISSUE #350: imprimitive type data: vertex/edge/path in map will crash the backend
**Describe the bug (__must be provided__)**

As title, minimal reproduce:

```
match (n:player) return {node: n}
```
or 
```
match p=(:player) return {p:p}
```
or
```
match ()-[e:follow]->() return {e:e} limit 10
```

**Your Environments (__must be provided__)**

* OS: Linux,Mac or Windows
* Node-version: `node --version` 
* Studio-version: display in studio navBar

**How To Reproduce(__must be provided__)**

1. Step 1, open console
2. Step 2, run `match (n:player) return {node: n}`

**Expected behavior**

no crash

### PR DESCRIPTION
**Pull request by hetao92**
fix #350 
fix the problem that the import task log is messed up
fix parameter in console

### CODE REVIEW

File: app/stores/console.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export const splitQuery = (query: string) => {
     const { gqlList, paramList } = acc;
     const line = cur.trim();
     if(line.startsWith(':')) {
-      paramList.push(line);
+      paramList.push(line.replace(/;?$/gm, ''));
```
Comment (huaxiabuluo) [inline app/stores/console.ts]: unnecessary `?`

File: server/api/studio/internal/service/gateway.go [hunk 2]
```diff
@@ -135,26 +135,25 @@ func (s *gatewayService) BatchExecNGQL(request *types.BatchExecNGQLParams) (*typ
...
-
-	if len(paramList) > 0 {
-		execute, _, err := dao.Execute(NSID, "", paramList)
-		gqlRes := map[string]interface{}{"gql": strings.Join(paramList, "; "), "data": execute}
+	for _, gql := range gqls {
+		execute, _, err := dao.Execute(NSID, gql, make([]string, 0))
+		gqlRes := map[string]interface{}{"gql": gql, "data": execute}
 		if err != nil {
+			isSErr := isSessionError(err)
+			if isSErr {
```
Comment (huaxiabuluo) [inline server/api/studio/internal/service/gateway.go]: `isSErr` seems strange, better to make it one line

```go
if isSessionError(err) {}
```

**Review by huaxiabuluo — COMMENTED** [review]
LGTM

**Review by huaxiabuluo — APPROVED** [review]
LGTM
