### PR TITLE
fix: fix some issues

### LINKED ISSUE #448: [控制台] 执行结果可视化快捷键未禁用
1. 控制台执行match (v) return v limit 100
2. 点击可视化 点击画布后点击Tab快捷键
3. 右侧详情被阻挡
image

### LINKED ISSUE #449: [草图] Tag超过256位字符报错 删除所有字符 报错未取消
失败状态未更新

### LINKED ISSUE #451: [草图] 使用草图创建空间 并删除空间 再次创建报错已存在
1. 使用草图创建test1的空间
2. Schema中找到test1并删除
3. 返回草图 再次创建test1的空间
4. 报错 空间已存在

草图删除空间后仍存在

### PR DESCRIPTION
**Pull request by hetao92**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
- fix #448 
- fix #449 
- fix #451

### CODE REVIEW

File: app/pages/SketchModeling/SchemaConfig/index.tsx [hunk 1]
```diff
@@ -67,14 +67,19 @@ const SchemaConfig: React.FC = () => {
     return invalid;
   };
   const handleUpdate = useCallback(
-    debounce((_, allValues) => {
+    debounce((changed, allValues) => {
```
Comment (huaxiabuluo) [inline app/pages/SketchModeling/SchemaConfig/index.tsx:70]: missing type

File: app/pages/SketchModeling/SchemaConfig/index.tsx [hunk 2]
```diff
@@ -36,7 +36,7 @@ const SchemaConfig: React.FC = () => {
     const name = form.getFieldValue('name');
     const data = sketchModel.editor?.schema.getData();
     let invalid = false;
-    if(!data || name === prevName) return sketchModel.active?.invalid || false;
+    if(!data || name === prevName) return false;
```
Comment (huaxiabuluo) [inline app/pages/SketchModeling/SchemaConfig/index.tsx]:
```ts
if(!data || name === prevName) return false;

let invalid = false;
```

**Review by huaxiabuluo — APPROVED** [review]
LGTM
