### PR TITLE
fix: fix issues

### LINKED ISSUE #601: Welcome Page Document Jump Failure
image

### LINKED ISSUE #602: Problems found after upgrading components
1. Template missing borders
image
2. Sketch properties Repeat error Incorrect color
image

### LINKED ISSUE #612: UI issue
1. 底色需确认是否正确
image
2.hover按钮位置偏移
image
3. 图标需确认是否正确
image

### LINKED ISSUE #613: 存在索引 取消定义属性 再次勾选 会自动ADD属性
image

### LINKED ISSUE #614: 上传文件 批量修改分隔符 输入框自动收起
上传文件修改分隔符 hover后 点击输入框会收起

### LINKED ISSUE #615: 欢迎页草图文案不正确
566c244792cd487643a92dc564643c06

### LINKED ISSUE #623: [导入] 选择VID列 选中后忽略 展开字符串拼接 前缀填写任意内容 触发兜底页
## 1. 选择VID为第一列 点击忽略
image
## 2. 展开前缀 填写任意字段
image
image

导入选择VID列之后点击忽略

### PR DESCRIPTION
**Pull request by hetao92**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
- fix #601 
- fix #602 
- fix #612 
- fix #613 
- fix #614 
- fix #615 
- fix #623

### CODE REVIEW

File: app/pages/Import/TaskCreate/SchemaConfig/FileMapping/index.tsx [hunk 1]
```diff
@@ -52,51 +51,47 @@ const VIDSetting = observer(
...
+            <div>
+              <span className={cls(styles.label, styles.required)}>{intl.get(`import.${label}`)}</span>
+              <CSVPreviewLink
+                onMapping={(index) => handleMapping(index)}
+                // @ts-ignore
+                file={data.file}
+                data={data[idKey]}
+                multipleMode={true}
+              >
+                {!data[idKey] || data[idKey].length === 0
```
Comment (huaxiabuluo) [inline app/pages/Import/TaskCreate/SchemaConfig/FileMapping/index.tsx:68]: `!data[idKey]?.length`

**Review by huaxiabuluo — APPROVED** [review]
LGTM
