### PR TITLE
fix: fix empty props in template import

### LINKED ISSUE #414: 使用YAML文件导入时的报错排查
想通过YAML文件导入ldbc数据集，但是通过返回的报错信息无法排查问题。
image

### PR DESCRIPTION
**Pull request by hetao92**
## What type of PR is this?
- [x] bug
- [ ] feature
- [x] enhancement

#### Description:
- fix #414 
- support multiple vid select in console
image
- optimize stats & disable event in sketch

### CODE REVIEW

File: app/pages/Console/ExportModal.tsx [hunk 1]
```diff
@@ -28,18 +28,19 @@ const ExportModal = (props: IProps) => {
...
+        ? tables.reduce((acc, cur) => {
+          if (cur.type === 'vertex') {
+            acc.push(cur.vid);
+          } else {
+            vertexIds.forEach(id => {
+              acc.push(cur[id].toString());
+            });
+          }
+          return acc;
+        }, []).filter(vertexId => vertexId !== '')
```
Comment (huaxiabuluo) [inline app/pages/Console/ExportModal.tsx]:
```ts
tables.reduce((acc, cur) => {
  if (cur.type === 'vertex') {
    cur.vid && acc.push(cur.vid);
  } else {
    vertexIds.forEach(id => {
      acc.push(cur[id].toString());
    });
  }
  return acc;
}, [])
```

File: app/pages/Schema/SchemaConfig/List/SpaceStats/index.tsx [hunk 2]
```diff
@@ -14,7 +14,17 @@ const SpaceStats = () => {
...
+    list: {
+      Type: string,
+      Name: string,
+      Count: number,
+    }[],
+    total: {
+      vertices: number,
+      edges: number,
+    } | null
+  } | null>(null);
```
Comment (huaxiabuluo) [inline app/pages/Schema/SchemaConfig/List/SpaceStats/index.tsx]:
```ts
const [data, setData] = useState<{
  list: { Type: string; Name: string; Count: number }[];
  total?: { vertices: number; edges: number };
}>({ list: [], total: undefined });
```

File: app/pages/Schema/SchemaConfig/List/SpaceStats/index.tsx [hunk 3]
```diff
@@ -44,13 +54,30 @@ const SpaceStats = () => {
...
+              vertex: 0,
+              edge: 0,
+            };
+          }
+          prev.total[cur.Name] = cur.Count;
+        } else {
+          prev.list.push(cur);
+        }
+        return prev;
+      }, { list: [], total: null });
```
Comment (huaxiabuluo) [inline app/pages/Schema/SchemaConfig/List/SpaceStats/index.tsx]:
```ts
const nextData = data.tables.reduce((prev, cur) => {
  if (cur.Type === 'Space') {
    prev.total ||= { vertex: 0, edge: 0 };
    prev.total[cur.Name] = cur.Count;
  } else {
    prev.list.push(cur);
  }
  return prev;
}, { list: [], total: undefined } as typeof data });
```

File: app/pages/Import/TaskList/TemplateModal/index.tsx [hunk 4]
```diff
@@ -50,6 +53,17 @@ const TemplateModal = (props: IProps) => {
             throw new Error(intl.get('import.fileNotExist', { name: file.path }));
           }
         });
+        // empty props in yaml will converted to null, but its required in nebula-importer
+        parseContent.files.forEach(file => {
+          if(file.schema.edge) {
+            file.schema.edge.props = file.schema.edge?.props || [];
```
Comment (huaxiabuluo) [inline app/pages/Import/TaskList/TemplateModal/index.tsx]: file.schema.edge.props ||= [];

File: app/pages/Import/TaskList/TemplateModal/index.tsx [hunk 5]
```diff
@@ -50,6 +53,17 @@ const TemplateModal = (props: IProps) => {
...
+          }
+          if(file.schema.vertex) {
+            file.schema.vertex?.tags.forEach(tag => {
+              tag.props = tag.props || [];
```
Comment (huaxiabuluo) [inline app/pages/Import/TaskList/TemplateModal/index.tsx]: `tag.props ||= [];`

**Review by huaxiabuluo — APPROVED** [review]
LGTM
